# Generated by Django 5.0.4 on 2024-04-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Имя')),
                ('short_description', models.TextField(max_length=100, verbose_name='краткое описание')),
                ('Full_description', models.TextField(max_length=250, verbose_name='полное описание')),
                ('price', models.FloatField(blank=True, verbose_name='цена')),
                ('quantity_in_stock', models.IntegerField(blank=True, verbose_name='количество на складе')),
            ],
        ),
    ]
